Clarify a few declarations for static analyzers
aurora-opensource/au pull request #317
Opened 2024-10-30 19:18 UTC by djehuti

Some static analyzers can have trouble with some of these templates; this PR separates them to help parsers that might have difficulty.

2024-10-30 19:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aurora-opensource/au?pullRequest=317) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aurora-opensource/au?pullRequest=317) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aurora-opensource/au?pullRequest=317) it.</sub>

2024-10-30 19:24 UTC, geoffviola commented on au/code/au/prefix.hh
> +    static constexpr detail::ExtendedLabel<1, U> label{detail::corncatenate("k", UnitLabel<U>::value).char_array()};
Nit: spelling 🌽

2024-10-30 19:35 UTC, chiphogg requested changes
If we end up landing these kinds of changes to appease static analyzers, we'll do it in a more production ready way.  I already have a good idea of how I plan to do most of these across the codebase, if it comes to that.

That said, I don't want to put any effort into reviewing/landing these changes until we understand whether the broader effort can succeed.  Given that this particular static analyzer does not understand function objects (!!), and that function objects are a core component of our public facing APIs, we need to find out whether they are able to fix their product or provide a workaround.

2024-10-31 14:21 UTC, djehuti commented
I deeply regret not having thought of "decorntaminate" before pushing that commit.

2024-12-02 18:46 UTC, chiphogg commented
We ended up deciding we didn't need this PR.

2024-12-02 18:46 UTC, closed without merging