Prefer specific feature test macros
aurora-opensource/au pull request #358
Opened 2024-12-12 19:25 UTC by matthew-reynolds

Rather than testing for the entire C++ standard revision using `__cplusplus`, use specific feature test macros for testing the presence of the particular features being used.

Testing the entire C++ standard revision is insufficient, as toolchains may implement and enable features incrementally during implementation of the next revision. A toolchain could feasibly implement three-way comparisons but have not yet incremented `__cplusplus` as other features remain unimplemented. [^1]

I also believe this approach to be somewhat more self-describing, which is appealing even in the face of its verbosity/clunkiness.

[^1]: https://isocpp.org/std/standing-documents/sd-6-sg10-feature-test-recommendations#explanation-and-rationale-for-the-approach

2024-12-12 20:54 UTC, chiphogg requested changes
Thanks for this!

You should update the remaining `__cplusplus` instance, which I think is in the `cpp20_test.cc` file.  In fact... maybe we should just remove it?  Maybe the right move would be to specifically exclude any configurations that we _don't expect_ to support the feature.  We don't actually have such configurations, and likely never will, but I think this would leave us in a better place: right now, if it happened that _all_ configurations didn't support this (maybe we made a mistake with the macros), we would just silently not be running tests.

In retrospect, I wish I had taken this approach in the first place... but, it would have been more work, because we would have needed to _engineer_ a solution for gcc 10, and now we don't because with your change it will just work out of the box.  :slightly_smiling_face:

2024-12-12 21:46 UTC, matthew-reynolds commented
> You should update the remaining __cplusplus instance, which I think is in the cpp20_test.cc file.

I went back and forth on this, sounds like I should have included this diff after all :slightly_smiling_face:
```diff
diff --git a/au/code/au/cpp20_test.cc b/au/code/au/three_way_compare_test.cc
similarity index 88%
rename from au/code/au/cpp20_test.cc
rename to au/code/au/three_way_compare_test.cc
index 8469837..dce5caf 100644
--- a/au/code/au/cpp20_test.cc
+++ b/au/code/au/three_way_compare_test.cc
@@ -12,7 +12,8 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
-#if __cplusplus >= 202002L
+#if (defined(__has_include) && __has_include(compare)) && \
+     (defined(__cpp_lib_three_way_comparison_) && __cpp_lib_three_way_comparison >= 201711L)
 
 #include <compare>
 
```

> In fact... maybe we should just remove it? Maybe the right move would be to specifically exclude any configurations that we don't expect to support the feature. We don't actually have such configurations, and likely never will, but I think this would leave us in a better place: right now, if it happened that all configurations didn't support this (maybe we made a mistake with the macros), we would just silently not be running tests.
>
> In retrospect, I wish I had taken this approach in the first place... but, it would have been more work, because we would have needed to engineer a solution for gcc 10, and now we don't because with your change it will just work out of the box. :slightly_smiling_face:

Oh, is GCC 10 in the bucket of "Has three way compare but not the rest of C++20?" Gotcha. In that case, removing the checks altogether seems reasonable to me, maybe with a comment at the top of the file stating that all toolchains used for testing support three way comparisons even if they don't support the full C++20. I also think this is a good way to go, I will update the PR

2024-12-12 21:57 UTC, matthew-reynolds commented
>> Maybe the right move would be to specifically exclude any configurations that we don't expect to support the feature. We don't actually have such configurations, and likely never will
>
> Oh, is GCC 10 in the bucket of "Has three way compare but not the rest of C++20?" Gotcha.

I think I must have misunderstood. The non-C++20 configurations of all toolchains don't support this feature. Can you clarify what you're envisioning here?

2024-12-12 22:01 UTC, chiphogg commented
> > > Maybe the right move would be to specifically exclude any configurations that we don't expect to support the feature. We don't actually have such configurations, and likely never will
> > 
> > 
> > Oh, is GCC 10 in the bucket of "Has three way compare but not the rest of C++20?" Gotcha.
> 
> I think I must have misunderstood. The non-C++20 configurations of all toolchains don't support this feature. Can you clarify what you're envisioning here?

I just meant: remove all checks from the test file.  If a configuration isn't compatible, we'll exclude it manually.

We already have it set up in GH actions such that we won't run that test target unless `--std=c++20` is set.

2024-12-12 22:38 UTC, matthew-reynolds commented
> If a configuration isn't compatible, we'll exclude it manually.
> We already have it set up in GH actions such that we won't run that test target unless --std=c++20 is set.

Isn't this still opt-in? We've moved it up to the Bazel level with the `manual` tag, but it's still skipped by default and only included manually for particular configs. And since we don't have Bazel config settings for the standard version, we can't use `target_compatible_with` or similar.

I'm fine with dropping the checks from the test file and relying only on the Bazel target selection, it removes one level of redundancy and means accidentally including the file in the wrong test config will fail rather than silently passing, but I don't think this addresses "specifically exclude configurations that don't support the feature."

2024-12-12 23:14 UTC, matthew-reynolds commented
> I meant that if we had a toolchain that didn't have a `-std=c++20` mode, then we would need to tweak our GitHub Actions file to specifically exempt that toolchain from trying to run the C++20 tests.

Gotcha, I'm following now.

Sounds good. I will remove the feature checks from `cpp20_test.cc`. I'm also inclined to rename it `three_way_compare_test.cc` - Any objections?

2024-12-12 23:31 UTC, chiphogg commented
> > I meant that if we had a toolchain that didn't have a `-std=c++20` mode, then we would need to tweak our GitHub Actions file to specifically exempt that toolchain from trying to run the C++20 tests.
> 
> Gotcha, I'm following now.
> 
> Sounds good. I will remove the feature checks from `cpp20_test.cc`. I'm also inclined to rename it `three_way_compare_test.cc` - Any objections?

Thanks for asking --- I prefer the current name, because I want to limit the potential proliferation of special test files.  (There sure are a _lot_ of feature test macros!)  I'm fine only _running the tests_ on toolchains with full C++20 support; the important thrust of this PR is to improve support for _library end users_.  Also, if we provided concepts with the library someday, I'd want this file to be the clear home for those tests.

2024-12-12 23:42 UTC, chiphogg approved these changes
Thanks for making this accessible to a wider and more precise set of users!

2024-12-13 00:08 UTC, chiphogg commented
It's becoming an Au tradition to get a PR landed _immediately after_ a release is cut.  :grin:

2024-12-13 00:08 UTC, merged